kind = "web"
previewPath = "/"
title = "MediQuick"
version = "1.0.0"
id = "artifacts/mediquick-app"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 21604

[services.development]
run = "pnpm --filter @workspace/mediquick-app run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/mediquick-app", "run", "build" ]
publicDir = "artifacts/mediquick-app/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "21604"
BASE_PATH = "/"
